auto_populate/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('person/', views.create, name="create"),
    path('create/', views.employee_form_view, name="employee_form_view"),
    path('', views.fetch_person_details, name='fetch_person_details'),
    # path('<int:pk>/', views.category_update, name='category_update'),
    # path('delete/<int:pk>/', views.category_delete, name='category_delete'),   
]

sale/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('create/', views.SaleCreateView.as_view(), name='create'),
    path('', views.SaleView.as_view(), name='sale_read'),
    path("bill/<billno>", views.SaleBillView.as_view(), name="sale_bill"),
]

test_dj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/', include('stock.urls')),
    path('merchandiser/', include('merchandiser.urls')),
    path('supplier/', include('supplier.urls')),
    path('purchase/', include('purchase.urls')),
    path('sale/', include('sale.urls')),
    path('category/', include('category.urls')),
    path('store/', include('store.urls')),
    path('fabric_requisition/', include('fabric_requisition.urls')),
    path('purchase_order/', include('purchase_order.urls')),
    path('store2/', include('store2.urls')),
    path('testapp/', include('testapp.urls')),
    path('auto_populate/', include('auto_populate.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auto_populate/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    city = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    city = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

auto_populate/forms.py
from django import forms
from .models import Employee, Person
from django.db import models
from django.forms import fields, Widget

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['person'].queryset = Person.objects.all()


class PersonForm(forms.ModelForm):
    name = forms.CharField(label='Person Name', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Person Name'}), required=True, error_messages={'required':'Must Enter a Correct Name'})
    class Meta:
        model = Person
        fields = '__all__'
        widgets = {
            'phone' : forms.TextInput(attrs = {'class' : 'textinput form-control'}),
            'email' : forms.EmailInput(attrs = {'class' : 'textinput form-control'}),
            'city' : forms.TextInput(attrs = {'class' : 'textinput form-control'}),
        }

auto_populate/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Person
from django.contrib import messages
from .forms import PersonForm

# def my_form_view(request):
#     form = MyForm()
#     if request.method == 'POST':
#         form = MyForm(request.POST)
#         if form.is_valid():
#             # Process the form data
#             # ...
#             form.save()
#             messages.success(request, 'Auto Populate created successfully')
#             return redirect('get_person_details')
        
#     context = {
#         'form': form
#     }
#     return render(request, 'auto_populate/my_form.html', context)

# def get_person_details(request):
#     person_id = request.GET.get('person_id')
#     try:
#         person = Person.objects.get(id=person_id)
#         response = {
#             'phone': person.phone,
#             'email': person.email,
#             'city': person.city
#         }
#         return JsonResponse(response)
#     except Person.DoesNotExist:
#         return JsonResponse({'error': 'Person not found.'})
    
    
from django.shortcuts import render
from django.http import JsonResponse
from .forms import EmployeeForm

def employee_form_view(request):
    form = EmployeeForm()
    return render(request, 'auto_populate/my_form.html', {'form': form})

def fetch_person_details(request):
    person_id = request.GET.get('person_id')
    person = Person.objects.filter(id=person_id).first()

    if person:
        data = {
            'phone': person.phone,
            'email': person.email,
            'city': person.city
        }
    else:
        data = {}

    return JsonResponse(data)



def create(request):
    form = PersonForm()
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Person created successfully')
            return redirect('create')
    context= {
        'form': form
    }
    return render(request, 'auto_populate/create.html', context)

templates/auto_populate/create.html
{% extends 'base/base.html' %} 
{% block title %}create Merchandiser{% endblock title %} 
{% block body %} 
{% load crispy_forms_tags %}
{% load static %}		

<!--start page wrapper -->
<div class="page-wrapper">
	<div class="page-content">
		<!--breadcrumb-->
		<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
			<div class="breadcrumb-title pe-3">Forms</div>
			<div class="ps-3">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb mb-0 p-0">
						<li class="breadcrumb-item">
							<a href="{% static 'javascript:;' %}">
								<i class="bx bx-home-alt"></i>
							</a>
						</li>
						<li class="breadcrumb-item active" aria-current="page">Add New Merchandiser</li>
					</ol>
				</nav>
			</div>
			<div class="ms-auto">
				<div class="btn-group">
					<button type="button" class="btn btn-light">Settings</button>
					<button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown">
						<span class="visually-hidden">Toggle Dropdown</span>
					</button>
					<div class="dropdown-menu dropdown-menu-end dropdown-menu-lg-end">
						<a class="dropdown-item" href="{% static 'javascript:;' %}">Action</a>
						<a class="dropdown-item" href="{% static 'javascript:;' %}">Another action</a>
						<a class="dropdown-item" href="{% static 'javascript:;' %}">Something else here</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% static 'javascript:;' %}">Separated link</a>
					</div>
				</div>
			</div>
		</div>
		<!---end breadcrumb--->
		<div class="row">
			<div class="col-xl-9 mx-auto">
				<div class="ms-auto">
					<a href="{% url 'merchandiser_read' %}" class="btn btn-light radius-30 mt-2 mt-lg-0">
						<i class="bx bx-grid-alt"></i>Merchandiser Table
					</a>
				</div>
						{% comment %} 
				<h6 class="mb-0 text-uppercase">Text Inputs</h6> {% endcomment %}
						
				<hr/>
				<div class="card">
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}	
							<div class="form-row">
								<div class="form-group col-md-12 mb-0">
									<div class="controls">
										{{ form.name|as_crispy_field }}
									</div>
								</div><br>
								<div class="form-group col-md-12 mb-0">
									<div class="controls">
										{{ form.phone|as_crispy_field }}
									</div>
								</div><br>

                                <div class="form-group col-md-12 mb-0">
									<div class="controls">
										{{ form.email|as_crispy_field }}
									</div>
								</div><br>

                                <div class="form-group col-md-12 mb-0">
									<div class="controls">
										{{ form.city|as_crispy_field }}
									</div>
								</div><br>
							</div>

							<div class="form-actions">
								<button type="submit" class="btn btn-light">Save changes</button>
								<button type="reset" class="btn">Cancel</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	<!--end row-->
	</div>
</div>
<!--end page wrapper -->
{% endblock body %}

templates/auto_populate/my_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee Form</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_person').change(function() {
                var personId = $(this).val();

                $.ajax({
                    url: '/fetch_person_details/',
                    data: {
                        'person_id': personId
                    },
                    dataType: 'json',
                    success: function(data) {
                        $('#id_phone').val(data.phone);
                        $('#id_email').val(data.email);
                        $('#id_city').val(data.city);
                    }
                });
            });
        });
    </script>
</head>
<body>
    <h2>Employee Form</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>